server:
  port: 8098
spring:
  application:
    name: cloud-feign-hystrixfactory
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
logging:
  level:
    com.miracle.cloud.feign.UserFeignClient: info
feign:
  hystrix:
    enabled: true

