server:
  port: 8099
spring:
  application:
    name: cloud-feign
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${vcap.application.instance-id:${spring.application.instance-id:${random.value}}}
  client:
    service-url:
      defaultZone: http://root:123456@localhost:8761/eureka/
logging:
  level:
    com.miracle.cloud.feign.FeignProductClient: debug

# Feign使用的注意事项
# 1. 不能使用方法级别的组合注解，如GetMapping， PostNapping 只能使用RequestingMapping
# 2. 路径上的Pathvariable参数一定要指定value，否则会报错，找不到指定的参数
# 3. 不嫩将自定义的configuration包防止在启动类的字目录下，否则，如同Ribbon，所有的feignClient都会使用同一组encode， decode， contract

# Spring Cloud Netflix 默认情况下不提供以下bean，但是仍然从应用程序上下文中查找这些类型的bean以创建假客户机：
# Logger.Level
# Retryer
# ErrorDecoder
# Request.Options
# Collection<RequestInterceptor>
# SetterFactory
