server:
  port: 8699
spring:
  application:
    name: cloud-file-upload
  http:
    multipart:
      max-file-size: 2000MB
      max-request-size: 2500MB
  resources:
    static-locations: classpath:/static/
  mvc:
    static-path-pattern: /**
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true